[general]
	#
	#How dynamic assets are generated.
	#- NEVER: No asset will be generated. Use this if you have an external pack that adds assets for the block, otherwise you'll get missing assets everywhere
	#- RUN_ONCE: Assets will be generated once every session. Subsequent reloads of resource/data pack will not regenerate them even if assets might have changed as a consequence
	#- CACHED: Generate the assets on first boot and saves them to a cache folder in .minecraft/dynamic-data-pack-cache. If mods or packs change it will regenerate the cache. If not, subsequent reload won't generate anything and just read the cached ones as a normal pack.
	#- CACHED_ZIPPED: Generate the assets on first boot and saves them to a cache zip file in .minecraft/dynamic-data-pack-cache. If mods or packs change it will regenerate the cache. If not, subsequent reload won't generate anything and just read the cached ones as a normal pack.
	#- ALWAYS: Will always generate the assets & will be stored in memory. No cache is used. Unintuitively, this is often the fastest method as any disk access will be slow. 
	#Try and see what works best for you.
	#Allowed Values: NEVER, RUN_ONCE, CACHED, CACHED_ZIPPED, ALWAYS
	server_assets_generation_mode = "ALWAYS"
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allow the item_search or searchBar to be visible.
	tab_item_search = true
	#If set to true, then all of the generated items will not be put into the mod's tab.
	no_mod_creative_tab = false
	#Generate blocktype tags for every block type. This will be applied to all the mods that use the system not just EC. Can make pack a bit faster if its off. Turn off if you dont need it
	generate_blocktype_tags = true
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false
