#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.createfood]
			cream_cake_chorus_fruit = true
			cream_cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			chocolate_cream_cake_butterscotch = true
			chocolate_cream_cake_caramel = true
			chocolate_cream_cake_chocolate = true
			chocolate_cream_cake_dark_chocolate = true
			chocolate_cream_cake_toffee = true
			chocolate_cream_cake_white_chocolate = true
			chorus_fruit_cream_cake_sweet_berry = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.create_mf]
			cultural = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.luminous_nether]
			mushroom = true
			withered = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			spirit = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.leaves_type.create_mf]
			cultural = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.luminousworld]
			palm = true
			yellow_birch = true

		[types.leaves_type.luminous_nether]
			ash = true

		[types.leaves_type.biomeswevegone]
			flowering_palo_verde = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			spirit = true
			flowering_spirit = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.upgrade_aquatic]
			river = true

#Disables specific entries
[entries]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true
